version: '3.8'
services:
  prisma-api:
    container_name: prisma-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env.production

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.production
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: prisma-db
