---
name: Dokku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@v1.0.1
        with:
          git_remote_url: '${{ secrets.SSH_URL }}/imd2-prisma-backend'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          git_push_flags: '--force'
          
      - name: Notify
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://api.pushcut.io/v1/notifications/github_deploy_done?title=Deploy successfull&text=Master branch of imd2-prisma-backend applicaton was successfully deployed to dokku!'
          method: 'POST'
          customHeaders: "{\"API-key\": \"${{ secrets.PUSHCUT_API_KEY }}\"}"
